# Generated by Django 2.1.2 on 2018-11-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguaxe', models.CharField(max_length=50)),
                ('outra_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCompe', models.CharField(max_length=50)),
                ('software', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFin', models.DateField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=6)),
                ('compAdq', models.TextField()),
            ],
            options={
                'ordering': ['dataFin'],
            },
        ),
        migrations.CreateModel(
            name='DatosPersoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apel1', models.CharField(max_length=50)),
                ('apel2', models.CharField(max_length=50)),
                ('dataNac', models.DateField()),
                ('correoe', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=80)),
                ('numPis', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('letraPis', models.CharField(max_length=1)),
                ('concello', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.TextField()),
                ('empresa', models.TextField()),
                ('provincia', models.CharField(max_length=50)),
                ('concello', models.CharField(max_length=50)),
                ('funcions', models.TextField()),
                ('dataInicio', models.DateField()),
                ('dataFin', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['dataFin'],
            },
        ),
        migrations.CreateModel(
            name='FormOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacion', models.CharField(max_length=80)),
                ('dataInicio', models.DateField()),
                ('dataFin', models.DateField(blank=True, null=True)),
                ('escola', models.CharField(max_length=80)),
                ('informacionAdicional', models.TextField()),
            ],
            options={
                'ordering': ['dataFin'],
            },
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutroDato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.CharField(max_length=50)),
                ('texto2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='experienciaprofesional',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Sector'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='OutroDato',
            field=models.ManyToManyField(blank=True, null=True, to='cv.OutroDato'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='compInfor',
            field=models.ManyToManyField(blank=True, null=True, to='cv.CompInfor'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='compProg',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Comp_Prog'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Curso'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='datosPersoais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.DatosPersoais'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Direccion'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='experienciaProfesional',
            field=models.ManyToManyField(blank=True, null=True, to='cv.ExperienciaProfesional'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='formOficial',
            field=models.ManyToManyField(blank=True, null=True, to='cv.FormOficial'),
        ),
        migrations.AddField(
            model_name='compinfor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Niveis'),
        ),
        migrations.AddField(
            model_name='comp_prog',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Niveis'),
        ),
    ]
