# Generated by Django 2.1.2 on 2019-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compprog',
            name='nivel',
            field=models.CharField(blank=True, choices=[('p', 'Principiante'), ('m', 'Intermedio'), ('e', 'Experto')], default='p', max_length=1, verbose_name='Nivel'),
        ),
    ]
