# Generated by Django 2.1.2 on 2018-11-28 09:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cv', '0002_auto_20181128_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompProg',
            new_name='Comp_Prog',
        ),
    ]
