# Generated by Django 2.1.2 on 2018-11-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20181128_1039'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='Comp_Prog',
            new_name='CompProg',
        ),
    ]
