# Generated by Django 2.1.2 on 2019-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
